/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chanelling;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rashmi
 */
public class bill extends javax.swing.JFrame {
    
       Connection conn = connection.connect();

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
          setLocationRelativeTo(null);
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        lbldoc = new javax.swing.JLabel();
        lblbill = new javax.swing.JLabel();
        lblsoccharg = new javax.swing.JLabel();
        lblthost = new javax.swing.JLabel();
        lblDname = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDch = new javax.swing.JLabel();
        lblBill = new javax.swing.JLabel();
        lblHch = new javax.swing.JLabel();
        txtdetails = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbPatientId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PATIENT ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("E - Chanelling System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("PATIENT BILL ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 229, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("NAME");
        jPanel2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 146, 35));

        lbldoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldoc.setForeground(new java.awt.Color(255, 255, 255));
        lbldoc.setText("DOC NAME");
        jPanel2.add(lbldoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 146, 35));

        lblbill.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblbill.setForeground(new java.awt.Color(255, 255, 255));
        lblbill.setText("BILL AMOUNT");
        jPanel2.add(lblbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 237, 35));

        lblsoccharg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblsoccharg.setForeground(new java.awt.Color(255, 255, 255));
        lblsoccharg.setText("DOC CHARGES");
        jPanel2.add(lblsoccharg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 194, 35));

        lblthost.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblthost.setForeground(new java.awt.Color(255, 255, 255));
        lblthost.setText("HOSPITLE CHARGES");
        jPanel2.add(lblthost, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 261, 35));

        lblDname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDname.setForeground(new java.awt.Color(255, 204, 0));
        lblDname.setText("QQ");
        jPanel2.add(lblDname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 146, 47));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 204, 51));
        lblName.setText("QQ");
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 146, 35));

        lblDch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDch.setForeground(new java.awt.Color(255, 204, 0));
        lblDch.setText("AA");
        jPanel2.add(lblDch, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 146, 35));

        lblBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBill.setForeground(new java.awt.Color(255, 204, 0));
        lblBill.setText("AA");
        jPanel2.add(lblBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 146, 35));

        lblHch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHch.setForeground(new java.awt.Color(255, 204, 0));
        lblHch.setText("AA");
        jPanel2.add(lblHch, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 146, 35));

        txtdetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtdetails.setForeground(new java.awt.Color(255, 255, 255));
        txtdetails.setText("BILL DETAILS");
        jPanel2.add(txtdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 298, 45));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 2145, 102, 36));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 2144, 98, 37));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 720, 450));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHANEL ID");

        cmbPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPatientIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(cmbPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chanelling/Untitled-design-17.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1360, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPatientIdActionPerformed
        // TODO add your handling code here:
        
        String id = cmbPatientId.getSelectedItem().toString();
        System.out.println(id);
        
          try{
            
       
            PreparedStatement ps = conn.prepareStatement("Select * from chanel where id = ?");
            
            ps.setString(1,  id);
            
            ResultSet rs=ps.executeQuery();

            
            while(rs.next()){
                
                  lblName.setText( rs.getString("pname"));
                  lblDname.setText( rs.getString("Dname"));
                  lblDch.setText( rs.getString("doccharge"));
                  lblHch.setText( rs.getString("hoscharge"));
                  
                  float Total = Float.parseFloat(rs.getString("doccharge")) + Float.parseFloat(rs.getString("hoscharge"));
                  String tot = Float.toString(Total);
                  lblBill.setText( tot);

            }
            
            
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,"Error in Attendance Grid View..... "+e);
        }
        
        
        
        
        
    }//GEN-LAST:event_cmbPatientIdActionPerformed
  
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        

        try{
       Statement st = conn.createStatement();

         ResultSet r=st.executeQuery("select * from chanel ");

         while (r.next()) {  

             cmbPatientId.addItem(r.getString("id"));  
      }
         
       }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null,"Error in Attendance Grid View..... "+e);
        }
        
 
    }//GEN-LAST:event_formWindowOpened
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PatienLogin pl = new   PatienLogin();
        pl.setVisible(true);
        this.hide();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
                    PrintWriter out = new PrintWriter(new FileWriter("TestFile.txt"));
                    out.print(lblname.getText());
                    out.print(lbldoc.getText());
                    
                    out.flush();
                    out.close();

                } catch (IOException e1) {
                    System.err.println("Error occurred");
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        homePage1 nn = new homePage1();
        nn.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbPatientId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblDch;
    private javax.swing.JLabel lblDname;
    private javax.swing.JLabel lblHch;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblbill;
    private javax.swing.JLabel lbldoc;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblsoccharg;
    private javax.swing.JLabel lblthost;
    private javax.swing.JLabel txtdetails;
    // End of variables declaration//GEN-END:variables
}
